### ISSUE TITLE
Пропущенные стринги из базового функционала com_users

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#100]
COM_USERS_FRONTEND_LOGIN_SUCCESS
COM_USERS_FRONTEND_LOGOUT_SUCCESS

стрингов нет:
https://github.com/joomla/core-translations/blob/main/joomla_v4/translations/package/ru-RU/language/ru-RU/com_users.ini

базовые вещи входа и выхода с сайта не переведены.

![Снимок экрана 2023-05-12 в 22 20 26](https://github.com/JPathRu/localisation/assets/3432048/fccfb91e-57e5-4a30-a567-a85b6e0fd442)

**Comment by progreccor** [comment]
эти строки появились в версии joomla 4.3
посмотри ссылку изменений
https://github.com/joomla/core-translations/commit/70560d68b5b5559c66a8dde43111c29ca1b716cd

**Comment by Sulpher** [comment]
странно. может стринги переменовали. сообщения об авторизации/выходе всегда же были...  или нет?

**Comment by Kostelano** [comment]
Не были, https://github.com/joomla/joomla-cms/pull/30834.

Сообщение при входе удалили для будущей версии 4.3.2, https://github.com/joomla/joomla-cms/pull/40539.

**Comment by Kostelano** [comment]
Будет добавлено в версии [4.3.2](https://github.com/JPathRu/localisation/pull/101/files#diff-8650209dd64a879d7beb6c06486bc8afe0b9c398e9fc62f82785d362342bb83e).
