### ISSUE TITLE
Добавить ссылки на телеграм в сообщение после установки

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#105]
сообщение после установки. предлагаю в локализации добавить здесь ссылки на основные телеграм каналы.

<img width="602" alt="Снимок экрана 2023-10-29 в 14 44 18" src="https://github.com/JPathRu/localisation/assets/3432048/b5700bc3-9df1-4b11-b737-9a17eed8406c">

**Comment by Kostelano** [comment]
Опубликуй здесь эти основные каналы, пожалуйста

**UPD**
На главной в этой репе есть две ссылки:
- [Канал новостей Joomla в Telegram](https://t.me/joomlafeed),
- [Чат русскоязычного сообщества в Telegram](https://t.me/projoomla).

Есть ли еще какие-нибудь основные/важные каналы?

**Comment by Sulpher** [comment]
Я бы добавил еще это:
@joomlaru - https://t.me/joomlaru (еще один чат о Joomla)
@yoothemepro_joomla - https://t.me/yoothemepro_joomla (Стек разработчика: Yootheme Pro, Uikit)

**Comment by Kostelano** [comment]
https://github.com/JPathRu/localisation/commit/a4f2a750a3a4430e852aab6f2f22002cfe9e020b

![Screenshot_1](https://github.com/JPathRu/localisation/assets/8440661/3e93f008-1576-4d19-adf5-cd25e8601254)
