### ISSUE TITLE
Passkeys - не переведено

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#107]
версия перевода: 5.0.0
<img width="498" alt="Снимок экрана 2023-12-06 в 18 19 35" src="https://github.com/JPathRu/localisation/assets/3432048/35aee7e1-e0d1-4412-8cce-d5bb05e34680">

**Comment by Kostelano** [comment]
Термин не переводился, поскольку это название технологии/стандарта.

В форме авторизации [была замена WebAuthn на Passkeys](https://github.com/JPathRu/localisation/pull/106/files#diff-d0221b2aae4d21472545c0c75a33842d7613c93968711b2bb258382535eccd5dR39) для релиза 5.0.

![Screenshot_1](https://github.com/JPathRu/localisation/assets/8440661/852aa7ba-84de-483b-adb1-486ec3ddb10e)

Также доступно описание/подсказка:

`PLG_SYSTEM_WEBAUTHN_LOGIN_DESC="Войдите без пароля с помощью технологии Passkeys."`

Но почему-то в форме авторизации не вижу его.

**Comment by Kostelano** [comment]
Исправлено для 5.0.3 (https://github.com/JPathRu/localisation/commit/ea5de48cdaadc7cda8521fdb59a6561cef3a656e), релиз будет после выхода 5.0.4, т.к. минимум изменений.

Исправлено на "Войти без пароля".
https://github.com/JPathRu/localisation/commit/ea5de48cdaadc7cda8521fdb59a6561cef3a656e#diff-d0221b2aae4d21472545c0c75a33842d7613c93968711b2bb258382535eccd5dR39
