### ISSUE TITLE
Процесс работы над локализацией

### ISSUE THREAD

**Issue by wedal** [JPathRu/localisation#108]
Доброго дня!

Расскажите, пожалуйста, как строится процесс работы над локализацией. В частности интересует, выгрузка/загрузка, как сопоставляются константы в файлах en и ru версий: вручную или автоматически, есть ли следование порядку размещения констант в файле по аналогии с базовой версией.

В общем, поделитесь опытом =)

**Comment by b2z** [comment]
@Kostelano это больше к тебе 🙂

**Comment by Kostelano** [comment]
@wedal делаю все локально, никакими сторонними сервисами не пользуюсь. Так на мой взгляд быстрее.

1. Загрузил последний архив из репы к себе на ПК,
2. Далее перехожу в [Milestones](https://github.com/joomla/joomla-cms/milestones) к новой версии и переношу все новое в файлы у себя на ПК. Порядок размещения констант соблюдается всегда, потому что были случаи когда мне нужно было сравнить файл **en-GB** и **ru-RU** построчно.

Теперь **МОМЕНТЫ**. Ребята из репы Joomla тоже люди и тоже ошибаются. Поэтому не всегда и не ко всем PR проставлены milestones версии. Это значит, что по ссылке выше можно "пропустить" какой-то PR, т.к. его нет в списке, и, соответственно, не внести эти изменения в локализацию.

Поэтому, после внесения констант я еще сравниваю версии от Joomla к Joomla. Предположим, мы вносим изменения в 5.0.2 начиная с версии 5.0.0, здесь же на странице в браузере поиск по `/en-GB/` и я быстро нахожу константы, которые не внес (если такие вообще существуют к данной конкретной версии). Ссылка для сравнения версий:

`https://github.com/joomla/joomla-cms/compare/5.0.0...5.0.2` (вкладка **Files changed**)

Таким же образом вносятся **ВСЕ** новые константы локализации, если Joomla закрыла какой-то серьезный баг безопасности - они не создают PR по понятным причинам, а коммитят непосредственно перед релизом.

3. Внес константы, в папке на ПК удалил "старые" по дате файлы, новые в той же структуре папок загрузил в репу локализации. Не забываем и об изменении версии в файлах XML.

4. Далее снова загрузил последний архив к себе на ПК, удалил "лишние файлы" (например, в нашей репе это `installation`, `Glossary`, `README.md`), переименовал архив в `ru-RU_joomla_lang_full_5.0.2v1.zip` (так требует [раздел локализации Joomla](https://downloads.joomla.org/language-packs)), залил туда же и в раздел релизов нашей репы.

Что касается поиску/изменений по тексту, то пользуюсь **Total Commander**:

![Screenshot_2](https://github.com/JPathRu/localisation/assets/8440661/2f274176-eedb-4a75-8def-cfa345fdbcde)

Далее вываливается список с файлами, которые содержат "какой-то текст".

Если есть еще вопросы, задавай, может чего забыл упомянуть, но в целом подход такой. Набив руку, все очень быстро получается.

**Comment by Kostelano** [comment]
Забыл упомянуть, что настроена синхронизация с нашей репы в [Core-translations](https://github.com/joomla/core-translations). Все, что вносится здесь - появляется на следующий день там.

Опять же есть **НО**. Это не работает с файлом локализации папки инсталляции, потому что они очень любят и лелеют [Crowdin](https://ru.crowdin.com), забирая файлы инсталляции оттуда для большинства существующих языков Joomla. Для **ru-RU** приходится отдельно [заливать](https://github.com/joomla/core-translations/pull/919) файлы `installation/language/ru-RU`, которые в конечном итоге все же [попадают в релиз Joomla](https://github.com/joomla/joomla-cms/pull/42669).

**Comment by wedal** [comment]
@Kostelano, спасибо за такой развернутый ответ! В целом все понятно. Ручной работы все равно получается много. Хотя, если изменения в языковых файлах от версии к версии минимальны, то должно получаться достаточно быстро. 

Хорошо, если проект хостится на Github, как Joomla. Но может быть и другой хостинг. Если мы рассмотрим локализацию абстрактного компонента, который хранится на абстрактном хостинге, что изменится? Имеет ли смысл использовать Crowdin? Почему вы не пользуетесь им, а делаете локализацию вручную? 

Есть в голове примерный алгоритм того, как ускорить процесс переноса новых констант: 

1) Берем одинаковые файлы из русской (устаревшей), английской (устаревшей) и английской (обновленной) локализации,
2) Сканируем построчно английский новый файл,
3) Ищем в русском файле текущую строчку из английского нового файла,
4) Если такая строчка с переводом есть, то сравниваем ее значение в английском старом и английском новом файлах (совпадают -> идем дальше, не совпадают -> помечаем для анализа, как в п5)
5) Если строчки нет, то вставляем ее из английского нового в русский файл, для быстрого поиска в выходном файле предваряем эту строчку, например, звездочками.

На первый взгляд, простая в реализации программа получается. И, кажется, что она уже должна существовать =). Если делать это средствами git и/или IDE, то все изменения мы увидим, но переносить файлы все равно придется вручную, что, вероятно, значительно дольше.

**Comment by Kostelano** [comment]
> Хотя, если изменения в языковых файлах от версии к версии минимальны, то должно получаться достаточно быстро.

Именно так чаще всего. Для мажорных версий бывает чуть больше.

> Если мы рассмотрим локализацию абстрактного компонента, который хранится на абстрактном хостинге, что изменится?

Ничего не изменится, если есть способ "получить" или "увидеть" новые строки, не пересматривая и не сравнивая файлы целиком.

> Имеет ли смысл использовать Crowdin? Почему вы не пользуетесь им, а делаете локализацию вручную?

Может быть и имеет смысл, но это скорее вопрос привычки. Учитывая, что справляюсь быстро, мне облом добавлять дополнительный сервис, который точно не ускорит и так быстрый процесс.

Что касается описанного алгоритма, то мне не кажется он простым )). Что может быть проще, когда ты видишь конкретные **N** файлов, в которых в конкретное место внесли определенные строки? Это возвращаясь к пункту 2 предыдущего моего ответа.

Лично я не пользовался (только устанавливал, потестировал совсем немного), но для Joomla 4 был написан компонент [J4Localise](https://github.com/infograf768/j4localise) (также есть более старая версия [com_localise](https://github.com/infograf768/com_localise)), который был предназначен для локализации.

**Comment by wedal** [comment]
@Kostelano, спасибо, что поделились опытом. Стало гораздо понятнее. Можно закрывать вопрос или оставить открытым для предложений по совершенствованию процесса =).
