### ISSUE TITLE
Проверка ссылок в разделе справка

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#111]
смотрим раздел "справка"
<img width="457" alt="Снимок экрана 2024-03-14 в 23 08 48" src="https://github.com/JPathRu/localisation/assets/3432048/89daeb76-45cc-4b43-a1d2-c79f1c1736dd">

стек изменений - ссылка на:
https://joomla.stackexchange.com/

это не переводится. можно написать так:
Joomla на StackExchange

и еще.
Документация. предлагаю направлять сюда: https://joomlaportal.ru/documentation
 Официальный русский форум - здесь ссылка такая: 
https://домен/administrator/index.php?option=com_admin&view=help&layout=langforum
ведет на русский раздел официального форума joomla. этот раздел мертв. 
предлагаю кидать на joomlaforum.ru. этот  форум почти не развивается, но поактивнее, чем официальный.

**Comment by Kostelano** [comment]
> стек изменений - ссылка на: https://joomla.stackexchange.com/
> это не переводится. можно написать так: Joomla на StackExchange

Поправим.

> и еще. Документация. предлагаю направлять сюда: https://joomlaportal.ru/documentation Официальный русский форум - здесь ссылка такая: [https://домен/administrator/index.php?option=com_admin&view=help&layout=langforum](https://%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD/administrator/index.php?option=com_admin&view=help&layout=langforum) ведет на русский раздел официального форума joomla. этот раздел мертв. предлагаю кидать на joomlaforum.ru. этот форум почти не развивается, но поактивнее, чем официальный.

Эти ссылки вшиты в код, мы не можем их изменить.

**Comment by Kostelano** [comment]
Будет исправлено для Joomla 5.1 Stable.

https://github.com/JPathRu/localisation/pull/110/commits/7bb8b21a15ed67bf19f702d3ebae65a14f43cd45#diff-49ab1f3dbf86763947b830d2b52130f9067eb77ca9bf4e6b408de140129a16a3R85
