### ISSUE TITLE
Неверный перевод строк относительно brotli

### ISSUE THREAD

**Issue by progreccor** [JPathRu/localisation#113]
https://github.com/JPathRu/localisation/blob/9e49b0d2ec260fa8c8bf66a8629f9cda030817a4/administrator/language/ru-RU/com_admin.ini#L144

ссылка на строку

вот оригинал 
 
    COM_ADMIN_POSTINSTALL_MSG_HTACCESS_BROTLI_DESCRIPTION="<p>Before 4.4.4 the default htaccess.txt did not support Brotli compression. This could result in double compression errors when Joomla is installed on a server that uses Brotli compression. You should manually apply the necessary changes to any existing .htaccess file, as this file can not be updated automatically.</p><p>The old code:</p><pre>RewriteRule \"\.css\.gz$\" \"-\" [T=text/css,E=no-gzip:1]<br>RewriteRule \"\.js\.gz$\" \"-\" [T=text/javascript,E=no-gzip:1]</pre><p>The new code:</p><pre>RewriteRule \"\.css\.gz$\" \"-\" [T=text/css,E=no-gzip:1,E=no-brotli:1]<br>RewriteRule \"\.js\.gz$\" \"-\" [T=text/javascript,E=no-gzip:1,E=no-brotli:1]</pre>"

    
   COM_ADMIN_POSTINSTALL_MSG_HTACCESS_BROTLI_TITLE=".htaccess Update Brotli Compression"

перевод заголовка 

   COM_ADMIN_POSTINSTALL_MSG_HTACCESS_BROTLI_TITLE="Обновление .htaccess для  Brotli Compression"
   
   COM_ADMIN_POSTINSTALL_MSG_HTACCESS_BROTLI_DESCRIPTION="<p>До версии 4.4.4 стандартный файл htaccess.txt не поддерживал работу с Brotli сжатием. Это могло привести к ошибкам двойного сжатия, если компрессия Brotli была включена на сервере. Вам следует вручную применить указанные изменения в файле .htaccess, поскольку он не может быть изменен автоматически.</p><p>Было:</p><pre>RewriteRule \"\.css\.gz$\" \"-\" [T=text/css,E=no-gzip:1]<br>RewriteRule \"\.js\.gz$\" \"-\" [T=text/javascript,E=no-gzip:1]</pre><p>Обновленный код:</p><pre>RewriteRule \"\.css\.gz$\" \"-\" [T=text/css,E=no-gzip:1,E=no-brotli:1]<br>RewriteRule \"\.js\.gz$\" \"-\" [T=text/javascript,E=no-gzip:1,E=no-brotli:1]</pre>"

Сейчас перевод указывает на то, что якобы Joomla автоматически включает brotli сжатие. Это не так!

Это всего лишь исправления для тех серверов, где уже работает brotli.

иначе админка падает.

**Comment by Kostelano** [comment]
Согласен, поспешил. В PR https://github.com/joomla/joomla-cms/pull/43055 четко написано об этом:

===
**Actual result BEFORE applying this Pull Request**
**If your hosting does not use brotli**
Joomla works properly

**If your hosting use brotli**
Joomla in HTTP works correctly.
Joomla in HTTPS does not load the CSS and JS resources, and investigating the error in the console is: `ERR_CONTENT_DECODING_FAILED`

===
**Expected result AFTER applying this Pull Request**
**If your hosting does not use brotli**
Joomla still works properly

**If your hosting use brotli**
Joomla works properly
