### ISSUE TITLE
Переименовать термин Схема на Микро-разметка или schema.org

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#114]
<img width="955" alt="Снимок экрана 2024-04-26 в 12 01 56" src="https://github.com/JPathRu/localisation/assets/3432048/24c96736-61e6-4505-935a-982d8d4232cc">

Какая такая схема?
нужно кликнуть и станет ясно.
давайте назовем вкладку Schema.org или микро-разметка.

**Comment by Kostelano** [comment]
Исправлено для будущей новой версии пакета, https://github.com/JPathRu/localisation/commit/08f103a6e3373d5656195cba7ec0e6addae4dd5d.
