### ISSUE TITLE
joomla 4.4.5 - Не удалось обновить плагинА

### ISSUE THREAD

**Issue by sergeytolkachyov** [JPathRu/localisation#115]
![image](https://github.com/JPathRu/localisation/assets/6236403/1ed34bd2-e8dc-453a-9a7f-7d3ef243eb41)

**Comment by Kostelano** [comment]
Увы, проблема склонения.

В зависимости от установки/обновления, ошибки установки/обновления используются строки:

```
COM_INSTALLER_INSTALL_SUCCESS="Установка %s успешно завершена."
COM_INSTALLER_MSG_UPDATE_SUCCESS="Обновление %s успешно завершено."
COM_INSTALLER_MSG_UPDATE_ERROR="Не удалось обновить %s."
```

Где переменная:

```
COM_INSTALLER_TYPE_TYPE_COMPONENT="компонента"
COM_INSTALLER_TYPE_TYPE_FILE="файла"
COM_INSTALLER_TYPE_TYPE_LANGUAGE="языка"
COM_INSTALLER_TYPE_TYPE_LANGUAGEPACKAGE="языкового пакета"
COM_INSTALLER_TYPE_TYPE_LIBRARY="библиотеки"
COM_INSTALLER_TYPE_TYPE_MODULE="модуля"
COM_INSTALLER_TYPE_TYPE_PACKAGE="пакета"
COM_INSTALLER_TYPE_TYPE_PLUGIN="плагина"
COM_INSTALLER_TYPE_TYPE_TEMPLATE="шаблона"
```

```
        if (!$installer->update($package['dir'])) {
            // There was an error updating the package
            $app->enqueueMessage(
                Text::sprintf(
                    'COM_INSTALLER_MSG_UPDATE_ERROR',
                    Text::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($package['type']))
                ),
                'error'
            );
            $result = false;
        } else {
            // Package updated successfully
            $app->enqueueMessage(
                Text::sprintf(
                    'COM_INSTALLER_MSG_UPDATE_SUCCESS',
                    Text::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($package['type']))
                ),
                'success'
            );
            $result = true;
        }
```

Пока не уверен как лучше решить проблему или ее вообще не решать, поскольку (чаще всего) будет успешное завершение установки/обновления, т.е. предложение без ошибок.

Если есть предложение - напиши.

**Comment by progreccor** [comment]
Если переставить местами - "Плагин не удалось обновить"
"Компонент не удалось обновить"
и так далее - это должно решить проблему.

"Компонент успешно установлен"
"Компонент успешно обновлен"

**Comment by Kostelano** [comment]
Уже есть строка с ошибкой установки "такого-то типа расширения", изменил на такую же формулировку относительно ошибки обновления.

```
COM_INSTALLER_INSTALL_ERROR="Ошибка установки %s."
...
COM_INSTALLER_MSG_UPDATE_ERROR="Ошибка обновления %s."
```
Joomla 4 https://github.com/JPathRu/localisation/commit/481213c58a8ba891ecfed311594759b5093877a4
Joomla 5 https://github.com/JPathRu/localisation/commit/c9f6bee9cfda4df69e8c04e6c77496bc98cfac7c
