### ISSUE TITLE
Обновить локализацию для Joomla 3?

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#116]
<img width="1043" alt="Снимок экрана 2024-06-09 в 12 29 50" src="https://github.com/JPathRu/localisation/assets/3432048/3560df26-4d5e-4d4e-b99c-94e02cc08a00">

Мы видим, что локализация еще не последняя, судя по версии.
есть ли смысл дообновить? или уже не стоит тратить время?

**Comment by Kostelano** [comment]
Смысл был, были даже какие-то изменения с последней выложенной версии 3.10.9.

Отправил на сервер, скоро придет обновление. Или можно скачать [здесь](https://github.com/JPathRu/localisation/releases/tag/3.10.12.1).
