### ISSUE TITLE
COM_USERS_MAIL_SEND_FAILURE_BODY

### ISSUE THREAD

**Issue by b2z** [JPathRu/localisation#118]
Из телеграм группы: 

В COM_USERS_MAIL_SEND_FAILURE_BODY есть ошибка - там два аргумента  %s ( com_users.ini). При регистрации пользователя на двуязычном сайте и неверном e-mail - ошибка 0. В английском  варианте - один аргумент %s. Если исправить перевод на "При отправке уведомления с данными пользователя произошла ошибка. Пользователь, который пытался зарегистрироваться: %s." - ошибки 0

**Comment by Kostelano** [comment]
Да, есть такое. Поправим для новых версий 4х и 5х.

Посмотрел чуть. Были изменения строки для 4х, но упустил, видимо. Т.к. в en-GB для Joomla 3.10.12 два аргумента:

> COM_USERS_MAIL_SEND_FAILURE_BODY="An error was encountered when sending the user registration email. The error is: %s The user who tried to register is: %s"

**Comment by Kostelano** [comment]
Исправлено для Joomla 4 https://github.com/JPathRu/localisation/commit/35482cb7e07916e2b6c8ac6eb5dae228f0b2eed7 и Joomla 5 https://github.com/JPathRu/localisation/commit/35482cb7e07916e2b6c8ac6eb5dae228f0b2eed7
