### ISSUE TITLE
Умный Поиск - Содержимое

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#22]
![Screen Shot 2019-11-08 at 03 11 42](https://user-images.githubusercontent.com/3432048/68438599-b2581400-01d5-11ea-85a7-de82a0ebdf9a.png)

Плагины:
Содержимое - Умный Поиск
Умный Поиск - Содержимое

Если не открывать описание, то просто переставлены фразы.
Перефразируем?

**Comment by Kostelano** [comment]
Мы здесь как-то обсуждали правильность использования терминов "контент", "содержимое", "материалы". Пришли к выводу, что "контент" - не камильфо и правильно использовать "Материалы".

Учитывая, что в оригинальных en-GB:
`PLG_CONTENT_FINDER="Content - Smart Search"`
`PLG_FINDER_CONTENT="Smart Search - Content"`

то переименовывать можно/нужно в 
`PLG_CONTENT_FINDER="Материалы - Умный Поиск"`
`PLG_FINDER_CONTENT="Умный Поиск - Материалы"`

Короче говоря, многое не поменяется :). Но надо переименовывать все заголовки плагинов, там слегка каша.

**Comment by Septdir** [comment]
Материалы !== Контентные плагины.
Контентные плагины используются в большинстве компонентов, а так же и в модулях и влияют на содержимое поэтому они и называются content a не articles

Вот на данном примере.
PLG_CONTENT_FINDER="Материалы - Умный Поиск" абсолютно не верно.
Потому что PLG_CONTENT_FINDER - это плагин, который позволяет использовать события
```
onContentAfterSave
onContentBeforeSave
onContentAfterDelete
onContentChangeState
onCategoryChangeState
```
В плагинах области finder. То бишь вырубив его фактически выключите весь умный поиск, а не только com_content

Поэтому если и переименовывать, то 
PLG_CONTENT_FINDER="Содержимое - Умный Поиск"
PLG_FINDER_CONTENT="Умный Поиск - Материалы"

**Comment by Kostelano** [comment]
Поддерживаю, четко и аргументировано.

**Comment by Sulpher** [comment]
Аналогично. Хорошее предложение.

**Comment by zikkuratvk** [comment]
Я вообще как бы наверное выступаю, за то, чтоб материалы привести к статьям... то есть ближе к переводу Joomla

**Comment by Kostelano** [comment]
**Контент - Умный Поиск**
https://github.com/JPathRu/localisation/pull/37/files#diff-5dafb3448df4cbe28145877974ce6afcR6
Предлагаю так по одной простой причине: все остальные плагины группы КОНТЕНТ именно так и называются. Если переименовать в СОДЕРЖИМОЕ, будет не красиво - 98% перевода пакета (сложилось исторически, как сказал  **zikkuratvk**) и в плагинах в частности именно слово КОНТЕНТ используется. Получается, если переименовывать в СОДЕРЖИМОЕ, то только все. В будущем это возможно, сейчас предлагаю так. Ваше мнение?

К вопросу "не русское слово" - да. Но в нашем языке и так достаточно нерусских слов, а в локализации Joomla и подавно.

**Умный Поиск - Материалы**
https://github.com/JPathRu/localisation/pull/37/files#diff-16d38677a074820474f662336234b09dR6
Тут понятно почему, выше https://github.com/JPathRu/localisation/issues/22#issuecomment-552043559 аргументировано написал **Septdir**.

**Comment by b2z** [comment]
Согласен

**Comment by b2z** [comment]
Будет исправлено в рамках #37
