### ISSUE TITLE
Незакрытая кавычка и неправильный перевод в 19 строке admin_ru-RU/ru-RU.com_cpanel.ini

### ISSUE THREAD

**Issue by progreccor** [JPathRu/localisation#25]
Незакрытая кавычка и неправильный перевод в 19 строке admin_ru-RU/ru-RU.com_cpanel.ini
Было:

> добавить следующие строки перед \ "## После Mod_rewrite . \»:

видно что стоит пробел после бекслеша, а вторые кавычки вообще елочкой. Сам перевод не дает понимания куда ставить (так перед или после?)

вот исправленная строка целиком:
`COM_CPANEL_MSG_ADDNOSNIFF_BODY="<p>Joomla теперь поставляется с дополнительными правилами безопасности в файлах htaccess.txt и web.config.txt по умолчанию. Эти правила отключают так называемую функцию прослушивания MIME-типа в веб-браузерах. Перехват приводит к определенным векторам атаки, где сценарии в обычно безвредных форматах файлов (например, изображения) будут выполняться, что приводит к уязвимости межсайтового скриптинга.</p><p>Команда безопасности рекомендует вручную применить необходимые изменения к существующим файлам .htaccess или web.config, поскольку эти файлы не могут обновляться автоматически.</p><p><strong>изменения для.htaccess</strong><br />добавить следующие строки перед _QQ_## Mod_rewrite in use._QQ_ :</p><pre>&lt;IfModule mod_headers.c&gt;\nHeader always set X-Content-Type-Options \"nosniff\"\n&lt;/IfModule&gt;</pre><p><strong>Changes for web.config</strong><br />Add the following lines right after \"&lt;/rewrite&gt;\":</p><pre>&lt;httpProtocol&gt;\n  &lt;customHeaders&gt;\n    &lt;add name=\"X-Content-Type-Options\" value=\"nosniff\" /&gt;\n  &lt;/customHeaders&gt;\n&lt;/httpProtocol&gt;</pre>"`

**Comment by Kostelano** [comment]
Все равно порезал теги GitHub (`_QQ_` -- не правильный тег).
Здесь я постил исправление для этой константы: 

https://github.com/JPathRu/localisation/pull/23/files#diff-95feaad47427ee5a46629320ac0f4356R19

**Comment by progreccor** [comment]
> 
> 
> Все равно порезал теги GitHub (`_QQ_` -- не правильный тег).
> Здесь я постил исправление для этой константы:
> 
> https://github.com/JPathRu/localisation/pull/23/files#diff-95feaad47427ee5a46629320ac0f4356R19

почему неправильный, если именно он и работает?

**Comment by Kostelano** [comment]
`"_QQ_"` так правильно,
`_QQ_` так не правильно (а именно так в вашем коде... порезало)

**Comment by zikkuratvk** [comment]
Приняты изменения которые это фиксят
