### ISSUE TITLE
Разные названия у "Языки контента"

### ISSUE THREAD

**Issue by Septdir** [JPathRu/localisation#26]
![изображение](https://user-images.githubusercontent.com/18382023/72790243-55052800-3c46-11ea-8fe9-40ccfe4c3218.png)

Получаться 3 разных тайтла.
1. Языки контента
2. Языки: Контент
3. Языки материалов

**Comment by zikkuratvk** [comment]
45ea2af52f88bec8ec6a6ff651d3982fe7b4f542 переименовано в контент, так как это получается самое близкое по смыслу
