### ISSUE TITLE
"Использовать глобальные" вместо "По умолчанию" ?

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#27]
![Screen Shot 2020-02-26 at 22 45 30](https://user-images.githubusercontent.com/3432048/75381489-e1f86c80-58e9-11ea-9ece-085aa3a7a32a.png)
![Screen Shot 2020-02-26 at 22 45 37](https://user-images.githubusercontent.com/3432048/75381491-e3299980-58e9-11ea-9d5c-8af9d029d097.png)

Сравните: в англ.версии Use global, в рус.версии - По умолчанию.

Может логично написать "Использовать глобальные"?

По длинне влазит:
![Screen Shot 2020-02-26 at 22 48 07](https://user-images.githubusercontent.com/3432048/75381635-23891780-58ea-11ea-9c0f-aca5c30667eb.png)

**Comment by Septdir** [comment]
Согласен, но надо смотерть где use glodal а где default

**Comment by Kostelano** [comment]
Не так и много мест, где используется Use Glodal:

![Screenshot_1](https://user-images.githubusercontent.com/8440661/77207326-c572dd00-6b01-11ea-89a2-9f413521e25a.png)

**Comment by Kostelano** [comment]
Здесь решили, что лучше использовать "По умолчанию" https://github.com/JPathRu/localisation/issues/7 :)

По сути "по умолчанию" - это так, как установлено где-то "выше" по иерархии, т.е. аналог "использовать глобальные", но короче, красивее и привычнее.

**Comment by b2z** [comment]
@Kostelano подловил @Sulpher =)) Вопросы закрываю, оставляем "По умолчанию"
