### ISSUE TITLE
Целостность пакета локализации

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#28]
Заметил интересную особенность. 
Взгляните на языковые пакеты:
![Screen Shot 2020-03-06 at 16 05 07](https://user-images.githubusercontent.com/3432048/76086219-bb5ec380-5fc4-11ea-981b-14c400cdc8cb.png)
![Screen Shot 2020-03-06 at 16 05 58](https://user-images.githubusercontent.com/3432048/76086225-bd288700-5fc4-11ea-9ccc-ea914bf5cd5c.png)

Язык комплектуется 3 пакетами:
French (fr-FR) Language pack - Package
French (France) - Site - Language 
French (France) - Administrator - Language

То есть, pkg и локализации фронта и админки.

А теперь взглянем, что у нас:
![Screen Shot 2020-03-06 at 16 11 02](https://user-images.githubusercontent.com/3432048/76086414-1a243d00-5fc5-11ea-8330-ccbee0238cdb.png)

Почему-то нет пакета локализации админки по аналогии с примером выше.
Что думаете по этому поводу?

**Comment by b2z** [comment]
Надо по другому сборку делать видимо

**Comment by Kostelano** [comment]
Добрый день!
На самом деле были все 3 пакета, но один из них был на русском языке.

Исправление + приведено в один формат во всех файлах: https://github.com/JPathRu/localisation/pull/29.

**Comment by b2z** [comment]
Поправили в #29
