### ISSUE TITLE
В файле /admin_ru-RU/ru-RU.com_installer.ini отсутствуют ключи/переводы

### ISSUE THREAD

**Issue by nvyush** [JPathRu/localisation#3]
В файле /admin_ru-RU/ru-RU.com_installer.ini отсутствуют ключи/переводы:
COM_INSTALLER_N_EXTENSIONS_PUBLISHED="%d расширений опубликовано."
COM_INSTALLER_N_EXTENSIONS_PUBLISHED_1="%d расширение опубликовано."
COM_INSTALLER_N_EXTENSIONS_PUBLISHED_2="%d расширения опубликованы."
COM_INSTALLER_N_EXTENSIONS_UNPUBLISHED="%d расширений снято с публикации."
COM_INSTALLER_N_EXTENSIONS_UNPUBLISHED_1="%d расширение снято с публикации."
COM_INSTALLER_N_EXTENSIONS_UNPUBLISHED_2="%d расширения сняты с публикации."

**Comment by zikkuratvk** [comment]
Добавлено
