### ISSUE TITLE
Не работает транслитерация алиасов

### ISSUE THREAD

**Issue by zikkuratvk** [JPathRu/localisation#35]
Мы не можем выпустить релиз пока не будет этот вопрос решен.

**Comment by Kostelano** [comment]
Не работает транслитерация определенных букв? Что именно?
Я попробовал создать несколько материалов, все прошло нормально, все заменилось.

**Comment by b2z** [comment]
Да, всё работает. Можно примеры? :)

**Comment by zikkuratvk** [comment]
Вообще в принципе транслитерация не работает. Скинул Диме в личку пример сайта.
На всех старых сайтах Joomla скорей всего не будет работать... если накатить этот пакет.

**Comment by b2z** [comment]
Очень, странно. Действительно, не работает. Дату и время текущие подставляет. Кстати, это такое же поведение, когда ты в английской админке пытаешься сохранить кириллическое название.

**Comment by zikkuratvk** [comment]
Короче не знаю по какой причине сбросился язык по умолчанию... на английски 
![image](https://user-images.githubusercontent.com/2261206/79150476-215f1780-7dc9-11ea-8518-a4f6e023de0b.png)
В чем глюк... не могу понять. Но в целом все работает, на других сайтах я такой проблемы не словил, так что пока закрываем.
