### ISSUE TITLE
Conservative caching = Стандартное кэширование?

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#38]
Собственно, сабж:
![Screen Shot 2020-04-24 at 22 07 00](https://user-images.githubusercontent.com/3432048/80248194-1da87c00-8678-11ea-9f58-c02dc29d337a.png)
![Screen Shot 2020-04-24 at 22 07 20](https://user-images.githubusercontent.com/3432048/80248200-1f723f80-8678-11ea-8b3c-c50c5888b932.png)

Я уже привык к стандартному кэшированию и консервативное только с толку сбивает. но, на всякий случай, напишу здесь, что термин вольный.

**Comment by b2z** [comment]
Ну если честно, я не против поменять.

**Comment by Kostelano** [comment]
Я тоже за то, чтобы корректно переведено было.
Я меняю кавычки в компонентах на локалке, добавил правильный перевод для кэширования. Позже пулл будет.

**Comment by zikkuratvk** [comment]
Ну значит закончится документация :-) хотя опять же... описание к стандартному кешированию по моему тоже не отвечает реальности. :-)

**Comment by Kostelano** [comment]
PR https://github.com/JPathRu/localisation/pull/40
https://github.com/JPathRu/localisation/pull/40/files#diff-bc59313ec7b9be5539f99f9c3623dc38R223

**Comment by progreccor** [comment]
> 
> 
> Я тоже за то, чтобы корректно переведено было.
> Я меняю кавычки в компонентах на локалке, добавил правильный перевод для кэширования. Позже пулл будет.

а правильный перевод - это какой?

**Comment by Kostelano** [comment]
`System Cache: (OFF - Caching disabled/ON - Conservative caching/ON - Progressive caching). Enable or disable caching and set caching level. Conservative level: smaller system cache, Progressive level (default): faster, bigger system cache, includes module renderers cache. Not appropriate for extremely large sites.`

Если **Консервативное кэширование** - неверно, подскажите как правильно.

**Comment by progreccor** [comment]
> Если **Консервативное кэширование** - неверно, подскажите как правильно.

ну давайте посмотрим традиционный перевод Lingvo

[Imgur](https://i.imgur.com/1Vysxbu.png)

**Comment by progreccor** [comment]
а второй кеш - не прогрессивный, а прогрессирующий

**Comment by Kostelano** [comment]
@progreccor, спасибо, пока развернул до:

```
COM_CONFIG_FIELD_VALUE_CACHE_CONSERVATIVE="Стандартное кэширование"
COM_CONFIG_FIELD_VALUE_CACHE_PROGRESSIVE="Прогрессирующее кэширование"
```
2b9b1a77ea51e7534fb6f3e7cb4e2023c1e98700

**Comment by b2z** [comment]
Что? Как это нет слова "Прогрессивный"? Ещё как есть и оно больше подходит, чем "Прогрессирующий". Второе больше похоже на действие во времени, что-то постоянно улучшается, прогрессирует, не стоит на месте.

Первое же часто используется именно как прилагательное.

**Comment by progreccor** [comment]
> Что? Как это "Прогрессивный" не подзодит? Оно больше подходит, чем "Прогрессирующий". Второе больше похоже на действие во времени, что-то постоянно улучшается, прогрессирует, не стоит на месте.
> 
> Первое же часто используется именно как прилагательное.

Дим, "прогрессивный" - это значит - современный, передовой.
progressive ничем прогрессивным не отличается от conservative. и не является чем-то более современным по сравнению с ним. Если мы пишем "прогрессивный" - это для русского человека означает что-то более лучшее, чем старое.
Грубо говоря, для русского это воспринимается так:
плохой кеш
хороший кеш.
И это неверно.
А прогрессирующий - это значит растущий, увеличивающийся, изменяющийся со временем. И это правильное отображение смысла кеша, который создает свою версию кеша, для каждого нового авторизованного посетителя.

**Comment by b2z** [comment]
Как хотите :)

**Comment by progreccor** [comment]
> 
> Как хотите :)
Если я ошибаюсь - аргументируй что не так

**Comment by progreccor** [comment]
кнопка close почему-то активна по умолчанию

**Comment by b2z** [comment]
Я своё мнение высказал, ничего нового не скажу :)

**Comment by DenysNosov** [comment]
> > Если **Консервативное кэширование** - неверно, подскажите как правильно.
> 
> ну давайте посмотрим традиционный перевод Lingvo
> 
> ![Imgur](https://camo.githubusercontent.com/4b0759b89cffff8ac4f2c3a208f6efb869d40a9e/68747470733a2f2f692e696d6775722e636f6d2f315679737862752e706e67)
> 
> Я бы предложил "традиционное кеширование"
> по сути - "стандартное кеширование" был близкий перевод.
> 
> можно еще "стабильный метод кеширования"

Традиционное и не традиционное кэширование 😂

**Comment by Kostelano** [comment]
https://github.com/JPathRu/localisation/pull/40/files#diff-bc59313ec7b9be5539f99f9c3623dc38

> COM_CONFIG_FIELD_VALUE_CACHE_OFF="Отключено"
> COM_CONFIG_FIELD_VALUE_CACHE_CONSERVATIVE="Стандартное кэширование"
> COM_CONFIG_FIELD_VALUE_CACHE_PROGRESSIVE="Прогрессивное кэширование"
