### ISSUE TITLE
Некорректные формы плюрализации (ошибка в localise.php)

### ISSUE THREAD

**Issue by Kostelano** [JPathRu/localisation#39]
Добрый день! Стал отвечать в discussions, но подумал, что об ошибке лучше здесь.

Итак, вероятно, нам не нужно изменение https://github.com/joomla/joomla-cms/pull/28763, поскольку это поможет другим языкам с кучей форм плюрализации, но не русскому. Мы не можем использовать `OTHER`, поскольку множественные формы на русском языке очень разные:

```
2 элемента
...
11 элементов
...
21 элемент
22 элемента
...
25 элементов
```
Но в нашем файле **localise.php** есть ошибка. Почему-то именно в некоторых разделах Joomla неверно выводятся строки плюрализации: например, если в Менеджере плагинов выделить 21 шт и включить/выключить, мы будем наблюдать следующее сообщение:

> Плагин успешно отключен.

Т.е. использовалась константа:

`COM_PLUGINS_N_ITEMS_UNPUBLISHED_1="Плагин успешно отключен."`

Более того, если мы выделим, например, 41 плагин, то получим сообщение, что отключен 1 плагин. Т.е. в упор берется константа `_1` для множественного числа. Для `_2`, `_3` все работает нормально, поскольку они переопределены.

----------------

Если мы повторим этот фокус, например, в Менеджере материалов, то там все будет в порядке:

> 11 материалов успешно снято с публикации.
> 21 материал успешно снят с публикации.

----------------

Если мы в настройках Менеджера пользователей выставим:
Вкладка **Пароль** --> **Минимальное кол-во цифр** --> **21**, то при регистрации на сайте получим:

> В пароле недостаточно цифр. Требуется не менее 1 цифры.

----------------

Я думаю, что нам следует расширить логику определения формы в **localise.php**, как минимум определяя и выводя отдельно `_1` и, возможно, `11, 111, 211...`

Сейчас так:
```
public static function getPluralSuffixes($count)
{
	if ($count == 0)
	{
		$return = array('0');
	} else {
		$return = array(($count%10==1 && $count%100!=11 ? '1' : ($count%10>=2 && $count%10<=4 && ($count%100<10 || $count%100>=20)? '2' : 'MORE')));
	}
	return $return;
}
```

**Comment by Kostelano** [comment]
Ребята, отбой. Сбило с толку, что выводится константа _1, но не обратил внимания, что там же нет переменной. Именно в ней проблема. Собственно, в оригинале тоже нет:
```
COM_PLUGINS_N_ITEMS_PUBLISHED_1="Plugin enabled."
COM_PLUGINS_N_ITEMS_UNPUBLISHED_1="Plugin disabled."
```

Вот это точно не правильно, переменная должна быть - только для английского языка так работает.

**Comment by Kostelano** [comment]
Поправил, примерно ~40% переменных отсутствовало для строк `_1`.
Позже залью.

**Comment by b2z** [comment]
OK, не будем внедрять string based suffixes.
