### ISSUE TITLE
Перевод для поля Title в форме создания материала

### ISSUE THREAD

**Issue by kkaazzoo** [JPathRu/localisation#4]
Привет, отсутствует перевод для поля Title в форме создания материала в админке. То же самое в форме создания категории. Также в форме создания категории поле Родительская категория переведена как Родительская метка.

**Comment by zikkuratvk** [comment]
Исправлено, на счет родительской

Но вот с тайтлом не понял 
![image](https://user-images.githubusercontent.com/2261206/54531530-7a8b2a80-49c0-11e9-904a-7db8f72cbf63.png)

**Comment by kkaazzoo** [comment]
У меня вот так
![2019-03-18_222410](https://user-images.githubusercontent.com/19167244/54557662-c3e17700-49cc-11e9-82ff-36925ca35753.png)

**Comment by kkaazzoo** [comment]
Можно закрывать. Причину бага пока поймать не могу, но локализация точно ни при чем.
