### ISSUE TITLE
Поправить таблицу транслитерации - убрать тире в случае мягкого знака

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#47]
мягкий знак заменяется на тире.

заголовок: альтернативная история
алиас: al-ternativnaya-istoriya

приходится тире убирать. неудобно. 
предлагаю поправить локализацию и пропускать тире в случае с мягким знаком

**Comment by progreccor** [comment]
с одной стороны я согласен.
с другой стороны получается два слова, которые отличаются только мягким знаком, будут генерировать один и тот же транслитерированный адрес

**Comment by Sulpher** [comment]
нужно исходить из того, какой вариант более распространен. 
сценарий, который я описал, встречается постоянно. 
сценарий. описанный тобой - реже. в этом случае уж лучше лишний символ дописать, быть внимательнее. к тому же, добавится нумерация, если что.

**Comment by Sulpher** [comment]
а чего не включили в последнюю сборку?

**Comment by Kostelano** [comment]
А нам и регистр символов важен? В файле https://github.com/JPathRu/localisation/blob/master/admin_ru-RU/ru-RU.localise.php

![Screenshot_2](https://user-images.githubusercontent.com/8440661/91664903-d5eca200-eafa-11ea-8afa-064485529cc8.png)

**Comment by Sulpher** [comment]
Ну бывает, когда  кто-то и в верхнем регистре напишет, логично поправить в обоих случаях.

**Comment by Kostelano** [comment]
Странное поведение.

1. Заливаю на локальный хост бэкап Joomla 3.9.11 (старая локализация без поддержки испанских букв и правки https://github.com/JPathRu/localisation/commit/444262204494b220b8df51384062ef33cbd148d8#diff-5655d319b2260ed3ba2a79add40309ff)
**ВОЛЬЕР => voler**

2. Обновляюсь до Joomla 3.9.21, но НЕ обновляю локализацию
**ВОЛЬЕР => voler**

3. Обновляю локализацию до 3.9.21 с поддержкой испанских букв
**ВОЛЬЕР => vol-er**

При всем при этом во всех версиях локализации неизменно правило `'' => 'ь'`
Чудеса.

Что это может быть? Откатим испанские буквы? Зачем они нам?

Пользователи уже тоже волнуются :)
https://joomlaforum.ru/index.php/topic,355508.msg1815430.html#msg1815430

**Comment by Sulpher** [comment]
ну нам важнее наш язык, конечно. а это точно испанские символы влияют?

**Comment by Kostelano** [comment]
Все, нашел ошибку, забецаю PR чуть позже.

Пропущена запятая в коде.

**Comment by Kostelano** [comment]
Потестите https://github.com/JPathRu/localisation/pull/50
