### ISSUE TITLE
Журнал действий - нужно локализовать пропущенные стринги

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#48]
Вся суть на картинке.
![chrome_ot73Wqg5aQ](https://user-images.githubusercontent.com/3432048/91279603-5d9a7f80-e78e-11ea-84e7-af095b842670.png)

User ABCD updated Joomla to 3.9.21

P.S. кстати, невозможно запомнить в русской версии перевод названия плагина, каждый раз переключаюсь на англ и ищу action logs и т.п.

**Comment by Kostelano** [comment]
Это не пропущенная строка, она добавлена в 3.9.21 и уже локализована :)

https://github.com/JPathRu/localisation/commit/4898070b8ac96d532a422b968db041928534e973
