### ISSUE TITLE
Record Hits - отслеживать просмотры?

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#49]
В оригинале так: Record Hits
Переведено: отслеживать просмотры

правильно было бы перевести как: записывать просмотры

в принципе, русская версия тоже понятная, но если говорить о переводе оригинала, то немного иная формулировка.

**Comment by Kostelano** [comment]
https://github.com/JPathRu/localisation/commit/8a303e78f9499253089f3e1ce2e806a3ec20df9e
