### ISSUE TITLE
tpl_atum.ini

### ISSUE THREAD

**Issue by dzandut** [JPathRu/localisation#55]
https://github.com/JPathRu/localisation/blob/j4/admin_ru-RU/tpl_atum.ini
https://github.com/JPathRu/localisation/blob/j4/glossary

ATUM="Atum - шаблон панели управления"
TPL_ATUM_BACK_TO_CONTROL_PANEL="Вернуться в панель управления"
TPL_ATUM_BACKEND_LOGIN="Joomla Administrator Login" - _думаю лучше перевести позже когда появится официальное название для этой части_
TPL_ATUM_COLORS_HUE="Выберите значение оттенка для темного цвета шаблона"
TPL_ATUM_COLORS_SETTINGS_BG_DARK_LABEL="Темный Фон"
TPL_ATUM_COLORS_SETTINGS_BG_LIGHT_LABEL="Светлый фон"
TPL_ATUM_COLORS_SETTINGS_CONTRAST_COLOR_LABEL="Контрастный цвет"
TPL_ATUM_COLORS_SETTINGS_LABEL="Настройки цвета"
TPL_ATUM_COLORS_SETTINGS_LINK_COLOR_LABEL="Цвет ссылки"
TPL_ATUM_COLORS_SETTINGS_LINK_SIDEBAR_COLOR_LABEL="Цвет ссылки на боковой панели"
TPL_ATUM_COLORS_SETTINGS_MONOCHROME_LABEL="Установить цвет на монохромный"
TPL_ATUM_COLORS_SETTINGS_SPECIAL_COLOR_LABEL="Специальный цвет"
TPL_ATUM_COLORS_SETTINGS_TEXT_DARK_LABEL="Темный текст"
TPL_ATUM_COLORS_SETTINGS_TEXT_LIGHT_LABEL="Светлый текст"
TPL_ATUM_IMAGE_LABEL="Изображение"
TPL_ATUM_IMAGE_SETTINGS_LABEL="Настройки изображения"
TPL_ATUM_LOGIN_LOGO_LABEL="Лого для страницы входа" - _Не дословный перевод, но мне кажется так понятней_
TPL_ATUM_LOGIN_SIDEBAR_VIEW_WEBSITE="посмотреть сайт"
TPL_ATUM_LOGIN_SITE_TITLE="%s - Administrator Login" - _думаю лучше перевести позже когда появится официальное название для этой части_
TPL_ATUM_LOGO_ALT_EMPTY_DESC="Декоративное изображение - описание не требуется"
TPL_ATUM_LOGO_ALT_EMPTY_LABEL="Нет описания"
TPL_ATUM_LOGO_ALT_LABEL="Описание изображения (замещающий текст в атрибуте "Alt")" - _Кавычки сработали но есть опасение что нужно всё-таки экранировать._
TPL_ATUM_MORE_ELEMENTS="Больше элементов"
TPL_ATUM_SITE_LOGO_LABEL="Крупное лого панели управления" - _Лого раскрытого меню_
TPL_ATUM_SITE_LOGO_SMALL_LABEL="Маленькое лого панели управления" - _Лого свернутого меню_
TPL_ATUM_SITENAME_LABEL="Название сайта"
TPL_ATUM_TOOLBAR="Панель инструментов"
TPL_ATUM_XML_DESCRIPTION="Продолжаем тему египетских богов/богинь (Khepri для 1.5, Hathor для 1.6, Isis для 3.0), Atum это имя шаблона для панели управления Joomla 4."  - _Это не дословный перевод, предлагаю как вариант. И думаю для Русского языка нет смысла выделять богинь так как множественное число включает обе группы._

**Изображения для удобства**
![image](https://user-images.githubusercontent.com/33223568/111870729-a8782080-8986-11eb-9f87-2e419591b753.png)
![image](https://user-images.githubusercontent.com/33223568/111870749-cd6c9380-8986-11eb-9fc6-f8787a8ee5d9.png)
![image](https://user-images.githubusercontent.com/33223568/111870770-e9703500-8986-11eb-9037-d4aa1bd67211.png)
![image](https://user-images.githubusercontent.com/33223568/111870784-0278e600-8987-11eb-910c-6d2475c6ff98.png)
![image](https://user-images.githubusercontent.com/33223568/111870814-20464b00-8987-11eb-9ba3-0d2386379e9e.png)
![image](https://user-images.githubusercontent.com/33223568/111870848-42d86400-8987-11eb-9264-7e810a51e2eb.png)
![image](https://user-images.githubusercontent.com/33223568/111870856-52f04380-8987-11eb-9af6-a0b6ab716bc5.png)

**Comment by b2z** [comment]
Привет, спасибо!

@JPathRu/localizers

**Comment by Kostelano** [comment]
Перевел вчера, файлы не залил еще.

**Comment by b2z** [comment]
@dzandut похоже, надо кооперироваться? А то вместе с @Kostelano двойную работу делать будете ;)

**Comment by dzandut** [comment]
Точно. Как бы нам это сделать?

**Comment by b2z** [comment]
@dzandut планируешь на постоянной основе локализацией заниматься? Я могу тебя в команду тут добавить, там можно обсуждать.

**Comment by dzandut** [comment]
Cтараюсь на постоянной основе заниматься, но не всегда есть такая возможность. Однако надеюсь смогу принести пользу вашей команде.

**Comment by Kostelano** [comment]
https://github.com/JPathRu/localisation/commit/699d9a7c5db5493fed9fe59f34db46f2396fc9cc

**Comment by Kostelano** [comment]
@dzandut оставь контакты свои или напиши на своей странице Github как связаться.

**Comment by b2z** [comment]
@dzandut я тебе кинул инвайт в команду. @Kostelano можем там общаться ;)

**Comment by dzandut** [comment]
Спасибо
