### ISSUE TITLE
При установке версии 4.0.0-rc4.1 из-под меню "Languages" пишется COM_INSTALLER_TYPE_TYPE_LANGUAGELANGUAGE

### ISSUE THREAD

**Issue by Bond97** [JPathRu/localisation#66]
Добрый день! Не знаю, это проблема самой Joomla 4 и надо создавать issue там, либо проблема от данного проекта, но при установке из-под меню Languages пишет в окне не language pack, а COM_INSTALLER_TYPE_TYPE_LANGUAGELANGUAGE.
Скриншот ниже прилагаю. Другие языки ставит нормально, с нормальным отображением надписи.

![изображение](https://user-images.githubusercontent.com/78050514/126479404-97cdf06d-3161-45d6-a490-5f252de71480.png)

Joomla 4 rc5-dev, php 8.0.8, latest nightly build.

**Comment by b2z** [comment]
Пока непонятно, но код, который за это отвечает нахожится здесь:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/src/Model/InstallModel.php#L216

```php
$msg = Text::sprintf('COM_INSTALLER_INSTALL_SUCCESS', Text::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($installLang . $package['type'])));
```

**Comment by Kostelano** [comment]
@Bond97 не могу воспроизвести. Как ты получаешь такую строку?

**Comment by b2z** [comment]
Всё таки больше похоже на то, что проблема именно в самой Joomla 4, потому что там по идее должно быть COM_INSTALLER_TYPE_TYPE_LANGUAGE. Либо некорректно $package['type'] определяется, либо ещё что-то.

А пробовали другой язык для интереса установить - такое же сообщение?

**Comment by b2z** [comment]
Попробовал у себя не тесте установить язык Welsh - сообщение Installation of the language pack was successful.
Устанваливаю русский, такая же проблема как и у @Bond97  
Installation of the COM_INSTALLER_TYPE_TYPE_LANGUAGELANGUAGE was successful.

@Kostelano надо поискать, откуда же это тянется.

**Comment by Bond97** [comment]
@b2z да, именно так, как в твоем последнем сообщении, любой другой язык - Installation of the language pack was successful, а русский- как в моем варианте.

@Kostelano настройки-установка языков- русский. Саму Joomla беру с https://developer.joomla.org/nightly-builds.html (Full package).

При переустановке языка точно так же выдаёт Installation of the COM_INSTALLER_TYPE_TYPE_LANGUAGELANGUAGE was successful

**Comment by Kostelano** [comment]
Там же тянет еще языки Joomla 3, если я не ошибаюсь.

**Comment by Bond97** [comment]
Там я не понял сам принцип, на одном хостинге тянет из 3 версии (cloudaccess.net), на другом (собственный VDS Fastpanel в Oracle cloud) - с 4 версии.

Но у меня с 4 версии подтягивает, в основном на своей VDS работаю, поэтому и написал про 4 версию пакета

**Comment by Kostelano** [comment]
Ошибку воспроизвел. Повторяется и на Joomla 3, но немного иначе: там наш пакет воспринимается системой не как пакет (package), а как **язык**, и, учитывая, что строки в файле SITE\administrator\components\com_installer\src\Model\InstallModel.php:

```
else
{
	// Package installed successfully.
	$msg = JText::sprintf('COM_INSTALLER_INSTALL_SUCCESS', JText::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($package['type'])));
	$result = true;
	$msgType = 'message';
}
```

выдает сообщение, что установлен **язык**. В то время, как установка других языковых пакетов завершается фразой **установлен пакет**.

В Joomla 4 немного изменили вывод, поэтому теперь наш пакет не просто **язык**, а **_LANGUAGELANGUAGE** вместо **_LANGUAGEPACKAGE**:

```
else
{
	// Package installed successfully.
	$msg = Text::sprintf('COM_INSTALLER_INSTALL_SUCCESS', Text::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($installLang . $package['type'])));
	$result = true;
	$msgType = 'message';
}
```

Т. е. у нас идентичная проблема в Joomla 3, но там ошибка незаметна.

Я точно не копировал файл манифеста с Joomla 3, а для Joomla 4 создавал новый на основе en-GB. Пока не могу сказать почему так.

**Comment by b2z** [comment]
По какой-то причине пакет воспринимается как язык.

**Comment by Kostelano** [comment]
PR https://github.com/JPathRu/localisation/pull/67 должен решить проблему + он также решает проблему https://github.com/JPathRu/localisation/pull/64#issuecomment-883913018 при синхронизации на [crowdin](https://joomla.crowdin.com/cms/ru).
