### ISSUE TITLE
Сократить фразу, чтобы были видны значения по умолчанию

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#7]
Вот как выглядит интерфейс в английской версии:
![Screen Shot 2019-04-05 at 14 13 12](https://user-images.githubusercontent.com/3432048/55623950-1da7b680-57ad-11e9-82a7-a1376785573e.png)

значение по умолчанию видно, это очень удобно. 
а вот как выглядит в русской локализации:
![Screen Shot 2019-04-05 at 14 13 17](https://user-images.githubusercontent.com/3432048/55624031-5c3d7100-57ad-11e9-8085-b3575cb9a82d.png)

нужно либо просить разработчиков расширить ширину выпадающего списка, либо делать  сокращение в локализации до **Исп. глобальное**

**Comment by b2z** [comment]
А может просто писать "По умолчанию (значение)"

**Comment by Sulpher** [comment]
> А может просто писать "По умолчанию (значение)"

отличная мысль. давайте так и сделаем. все просто и понятно.

**Comment by zikkuratvk** [comment]
Изменил на по умолчанию
