### ISSUE TITLE
Таблица транслитерации в J4 

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#74]
Локализация J4.

название: Главная страница
алиас такой: glavnaa-stranica

пересмотрите таблицу транслитерации

**Comment by Kostelano** [comment]
На сейчас в J3.10.2 такая же проблема не воспроизводится?
Пока не у ПК, проверю самостоятельно позже.

Таблица транслитерации в [J4 #L604](https://github.com/JPathRu/localisation/blob/j4/administrator/language/ru-RU/localise.php#L604) аналогична [J3 #L604](https://github.com/JPathRu/localisation/blob/master/admin_ru-RU/ru-RU.localise.php#L604) и была просто скопирована при создании локализации.

**Comment by Sulpher** [comment]
Так, я понял в чем причина: у меня был включен язык админки - en-GB и поэтому сработала транслитерация этой локализации. Вот как.  Может им напишем? все таки логично привести к единому стандарту.

**Comment by Kostelano** [comment]
Я не совсем понимаю, что подразумевается под единым стандартом. Логично, что английский язык срабатывает так, как задумано именно в их локализации и они не могут / не хотят поддерживать транслитерацию других яхыков в своем пакете по умолчанию.

**Comment by Sulpher** [comment]
> Я не совсем понимаю, что подразумевается под единым стандартом. Логично, что английский язык срабатывает так, как задумано именно в их локализации и они не могут / не хотят поддерживать транслитерацию других яхыков в своем пакете по умолчанию.

логика такая - если в каждом языке своя транслитерация, а английский - язык по умолчанию, то в нем не должно быть транслитерации, т.к. слишком много языков и стандартов.  а если они транслитерацию внедрили и потрудились сделать таблицу транслитерации кириллицы, то пусть сделают ее правильно.
Я  - ya
Ш - sh
Ч - ch
и т.д. 
просто предложить им нашу транслитерацию, раз они транслитерируют кириллицу.

**Comment by Kostelano** [comment]
У них нет транслитерации на уровне [localise.php](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/localise.php). Но суть понял, как вариант предложить можно конечно.

**Comment by b2z** [comment]
Интересно, а в каком файле происходит транслитерация, когда в английском интерфейсе кириллицу используешь?

**Comment by Sulpher** [comment]
> Интересно, а в каком файле происходит транслитерация, когда в английском интерфейсе кириллицу используешь?

может в твиттере спросить?

**Comment by b2z** [comment]
А есть ли смысл тратить время?

**Comment by Sulpher** [comment]
да наверное нет. это я любитель поставить англ в админке, чтобы быть ближе к оригиналу и для тестов, иногда забываю и вбиваю русские названия, а транслитерация срабатывает как описано выше. 90% так не делают.
