### ISSUE TITLE
Изменить термин количество столбцов

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#78]
фразу количество столбцов можно сократить до кол-во столбцов.
это не мешает, но так быстрее читается/воспринимается

<img width="1607" alt="Снимок экрана 2021-10-12 в 21 57 45" src="https://user-images.githubusercontent.com/3432048/137015744-0cfc6531-cc33-4407-81dc-2690b0d8cc46.png">

**Comment by Kostelano** [comment]
Не знаю как остальным, но мне больше нравится формулировка без сокращений там, где строка/фраза хорошо помещается. В админке J3 с этим были проблемы, поэтому там местами мы сокращали **Количество** до **Кол-во** и т. д. В J4 такой проблемы пока не видел.

Что касается в целом "сломанной" верстки из-за локализации, о которой ты написал в чате, то в первую очередь это конечно проблема самой админки, а не локализации - уж они бывают разные и русский язык в данном случае часто "страдает". Сейчас быстро не найду, но в [issue ](https://github.com/joomla/joomla-cms/issues) Joomla есть несколько постов с подобными сломанными страницами админки в какой-то другой локализации (кстати, в том числе **en-GB**). Надеюсь, это когда-то в будущем поправят.

Админка Joomla 4 на стадии alfa | beta имела чуть другую сетку, более неподходящую под наш язык, но потом шаблон перерисовали и улучшили ситуацию.
