### ISSUE TITLE
Privacy - Action Logs оставить в англ.версии

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#8]
Плагин в большинстве случаев не нужен,т.к.раздувает БД действиями.
плагин нужно отключить.
Запомнить название на  русском невозможно. Я помню, что это:
Privacy - Action Logs

приходится переключать админку на англ. чтобы поиском найти Action Logs.
полагаю, что это неудобно.
термин новый и неустоявшийся, поэтому запоминаешь его оригинальное название.

предлагаю оставить англ.версию: Privacy - Action Logs

**Comment by zikkuratvk** [comment]
Честно пока не знаю нужно ли это делать
