### ISSUE TITLE
Нужно поправить смысл в COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC

### ISSUE THREAD

**Issue by progreccor** [JPathRu/localisation#87]
`COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC="Максимальный размер загружаемого файла составляет менее 16MB. При попытке установки расширений могут возникнуть проблемы. Пожалуйста, измените значения переменных <strong>post_max_size</strong> и <strong>upload_max_filesize</strong> в файле <strong>php.ini</strong> (и/или <strong>.htaccess</strong>). Обратите внимание, что значение <strong>post_max_size</strong> должно быть больше, чем значение <strong>upload_max_filesize</strong>."
`

предлагаю изменить на такой 
`COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC="Максимальный размер загружаемого файла составляет менее 16MB. При попытке установки расширений могут возникнуть проблемы. Пожалуйста, измените значения переменных <strong>post_max_size</strong> и <strong>upload_max_filesize</strong> в файле <strong>php.ini</strong> (и/или <strong>.htaccess</strong>). Обратите внимание, что значение <strong>post_max_size</strong> должно быть больше или равно, чем значение <strong>upload_max_filesize</strong>."
`

Некоторые хостинг (ISPManager) не позволяют установить значение больше чем другое. Они их делают равными ( и строго говоря - это верно).
Несмотря на то, что в оригинале написано именно так, предлагаю текст изменить, так как уже были жалобы от людей, не сумевших выполнить рекомендацию.

**Comment by Kostelano** [comment]
Joomla 3:
https://github.com/JPathRu/localisation/commit/87601fd9a3786b460c6d57d0b9286b950570809b#diff-9df3c7f9e1a8e3ed1637fc14baba58f4d5a1426c3eb052617727559ab5bbc522R185
https://github.com/JPathRu/localisation/commit/87601fd9a3786b460c6d57d0b9286b950570809b#diff-9df3c7f9e1a8e3ed1637fc14baba58f4d5a1426c3eb052617727559ab5bbc522R188

Joomla 4:
https://github.com/JPathRu/localisation/pull/86/commits/8e0920d17ff1df3483f3318d4b273be8b0cdb114#diff-ddfd16d25272828734d758141669dd969bc4857fd9237620825596b599883fefR202
https://github.com/JPathRu/localisation/pull/86/commits/8e0920d17ff1df3483f3318d4b273be8b0cdb114#diff-ddfd16d25272828734d758141669dd969bc4857fd9237620825596b599883fefR205
