### ISSUE TITLE
Неверно перевели MOD_ARTICLES_NEWS_OPTION_INTROIMAGE

### ISSUE THREAD

**Issue by kernusr** [JPathRu/localisation#9]
MOD_ARTICLES_NEWS_OPTION_INTROIMAGE перевели, как "Вводный текст", а должно быть " Изображение для вступительного текста" или "Вступительное изображение"
![Annotation 2019-06-02 190524](https://user-images.githubusercontent.com/16020878/58763862-6a1f3080-8569-11e9-80c9-99f44c4831bc.jpg)

**Comment by zikkuratvk** [comment]
Исправлено
