### ISSUE TITLE
Плагины Конфиденциальность

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#90]
локализация плагинов Privacy Tool Suite. вот как я делаю, чтобы отсортировать плагины privacy tool suite. вбиваю в англ версии слово privacy.
в русской такого нет.  приходится переключаться на англ.

<img width="1265" alt="Снимок экрана 2022-07-18 в 17 28 30" src="https://user-images.githubusercontent.com/3432048/179533916-6d1d6ed9-9108-4b5c-b061-162cbcff1efc.png">

предлагаю локализацию поправить по аналогии с англ. : 
Privacy - [название плагина]
а надо:
Конфиденциальность - [название плагина]

**Comment by Kostelano** [comment]
Эти плагины "вместе" с компонентом **Персональные данные**, который был представлен в Joomla 3.9. На тот момент локализаторы перевели его так, с чем я полностью согласен, поскольку именно этот контекст и имеет данный компонент на 100%, учитывая запросы на экспорт/удаление данных с сайта.

Переименовать часть группы плагинов иначе - на мой взгляд плохая идея. Если и переименовывать, то все, что касается этого функционала. В любом случае здесь нужно общее решение. Свое мнение выразил.

К слову, поиск в заголовках плагина на любом кириллическом языке работает некорректно - давно известный баг. При поиске на русском сценарий возвращает все заголовки, которые **содержат** запрос, но **НЕ начинающиеся** с него (поиграйте с запросами `данные` или, например, `система`. В этом случае **Конфиденциальность** не спасет ;).

**Comment by Sulpher** [comment]
> К слову, поиск в заголовках плагина на любом кириллическом языке работает некорректно - давно известный баг.  

в таком случае нет смысла переименовывать...  а этот баг с поиском известен разрабам? хорошо бы issue составить...

**Comment by Kostelano** [comment]
Известен. Быстро не найду, но issue точно есть. Не уверен, что его хоть когда-нибудь починят )) Ему уже лет и лет.

**Comment by Kostelano** [comment]
> а этот баг с поиском известен разрабам? хорошо бы issue составить...

Нашел проблему с поиском среди плагинов, https://github.com/joomla/joomla-cms/issues/36300, хотя она была описана и кем-то ранее.

Закрываю, поскольку автор также выразил мнение, что переименование не имеет смысла.
