### ISSUE TITLE
Плагин доступности

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#91]
Текст такой:
`Плагин для интеграции на сайт панели доступности. После включения плагина панель можно открыть с помощью мыши, комбинации клавиш CTRL + ALT + A или CTRL + OPTION + A (MacOS).`

на маке вместо CTRL используется CMD (COMMAND).
исправьте неточность

**Comment by Kostelano** [comment]
Нет Мака, проверить не могу, но поверить могу :). В оригинальной en-GB [та же комбинация](https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/language/en-GB/plg_system_accessibility.ini#L28).
Можешь туда запостить проблему?

**Comment by Sulpher** [comment]
<img width="804" alt="Снимок экрана 2022-07-23 в 11 55 40" src="https://user-images.githubusercontent.com/3432048/180598108-a794d15a-756c-4db0-9e85-745057474539.png">

Да, стоит запостить.

сделал:
https://github.com/joomla/joomla-cms/compare/4.2-dev...Sulpher:joomla-cms:patch-1

**Comment by Kostelano** [comment]
Так а PR сделаешь? Они ж не узнают о коммите :).

**Comment by Sulpher** [comment]
если честно, то я в Github очень поверхностно ориентируюсь. увидел кнопку редактирования  и нажал, внес правку.
я - обычный юзер. по идее, должна быть проверка кем-то. иначе любой желающий внесет изменения и сломает систему.

**Comment by Kostelano** [comment]
Пожалуйста, сделай аналогичную правку в файле [plg_system_accessibility.sys.ini](https://github.com/Sulpher/joomla-cms/blob/patch-1/administrator/language/en-GB/plg_system_accessibility.sys.ini) в этой же ветке **patch-1**, я отправлю ПР от тебя. Или подтверди мой https://github.com/Sulpher/joomla-cms/pull/1.

**Comment by Sulpher** [comment]
Подтвердил твой. все правильно получилось?

**Comment by Kostelano** [comment]
Да, спасибо. Отправлен https://github.com/joomla/joomla-cms/pull/38322 в основную ветку.
