### ISSUE TITLE
Smart Search: слово 'обязательным' неверное

### ISSUE THREAD

**Issue by Sulpher** [JPathRu/localisation#95]
<img width="967" alt="Снимок экрана 2022-11-16 в 13 28 28" src="https://user-images.githubusercontent.com/3432048/202157428-6d65ea97-752f-4ff4-8c99-5b0342fe141b.png">

странная локализация smart search. ниже поля поисковая фраза и слово обязательным. я не понимаю, что это. нужно переключаться в англ версию

поиск is required 

<img width="962" alt="Снимок экрана 2022-11-16 в 13 31 15" src="https://user-images.githubusercontent.com/3432048/202157472-ffb1fba9-66e8-4568-aa13-09f99e3e7540.png">

так понятнее. поправить нужно локализацию

типа: abc является значением, обязательным к заполнению

длинная фраза, но раскрывает суть

**Comment by Kostelano** [comment]
Я не могу воспроизвести проблему.

Во-первых, в русской локализации последних N версий давно используется такая формулировка:

```
COM_FINDER_QUERY_RESULTS_0="Предполагая слово %2$s, ничего не найдено. <a href=\"#q\">Изменить запрос</a>"
COM_FINDER_QUERY_RESULTS_1="Предполагая слово %2$s, найден <a href=\"#search-result-list\">%d элемент</a>."
COM_FINDER_QUERY_RESULTS_2="Предполагая слово %2$s, найдено <a href=\"#search-result-list\">%d элемента</a>."
COM_FINDER_QUERY_RESULTS_MORE="Предполагая слово %2$s, найдено <a href=\"#search-result-list\">%d элементов</a>."
```

Где `%2$s` представляет собой:

```
COM_FINDER_QUERY_TOKEN_OPTIONAL="<span class=\"term\">%s</span> необязательным"
COM_FINDER_QUERY_TOKEN_REQUIRED="<span class=\"term\">%s</span> обязательным"
```

Это на 99% на мой взгляд близко к en-GB и вот почему. Умный поиск работает не только как стандартный поиск по фразе, а и с включением логических `и/или`. Соответственно, например фраза `joomla и вход или этапами` (фраза рабочая для установленных демо-данных блога) превращается в:

`Предполагая слово joomla обязательным, вход обязательным, этапами необязательным, найден 1 элемент.`

Как по мне, все звучит правильно.

Далее.

> abc является значением, обязательным к заполнению

Это неверно. И ничего общего не имеет с умным поиском.

**Comment by Sulpher** [comment]
не всегда смысл en-GB версии подходит к др.языкам. 
вариант короче: 
_'word' - обязательно к заполнению_

но тогда по смысловой нагрузке тоже ерунда. если  это значение уже заполнено, зачем об этом писать?

**Comment by Sulpher** [comment]
"Предполагая слово joomla обязательным, вход обязательным, этапами необязательным, найден 1 элемент."

так, конечно, по смыслу понятнее. но это уже логика компонента.

**Comment by Kostelano** [comment]
Потому что так написан код :). Если мы пишем запрос без логических и/или, это означает, что ВЕСЬ наш запрос является обязательным.

**Comment by Kostelano** [comment]
Ты опередил. Да, это логика компонента. И так уж написан код. Мы не можем для запроса без логических и/или избавиться от формулировки является ли запрос обязательным или нет.
