### ISSUE TITLE
Включите GitHub Pages для этой репы

### ISSUE THREAD

**Issue by korenevskiy** [JPathRu/localisation#96]
Пожалуйста включите Github Pages для этого репозитория. 
Чтобы можно было указывать прямой адрес на файл обновления XML в настройках Joomla

**Comment by b2z** [comment]
@korenevskiy поясни идею, пожалуйста

**Comment by korenevskiy** [comment]
Github Pages можно включить тут https://github.com/JPathRu/localisation/settings/pages
После чего в репу помещаете файл проверки обновлений translationlist_4.xml
И тогда доступ будет прямой к файлу обновлений.
https://JPathRu.github.io/localisation/translationlist_4.xml
Так в принципе правильно.
А остальные файлы версий пакетов как пологается прописываются внутри translationlist_4.xml
Для русскоязычных пользователей всегда будет доступен ресурс обновления локализации.

**Comment by Kostelano** [comment]
Не знаком с именно таким подходом, но реализовать "неофициальный" сервер обновлений с помощью этого репозитория довольно просто. Немного другим способом, без Github Pages.

Но на самом деле те, кто очень хочет обновить локализацию, просто качает ее и устанавливает, а остальные предпочитают задавать на форуме вопрос типа "что делать, не могу скачать / установить обновление".

**Comment by korenevskiy** [comment]
Вы предлагаете жителям всей России с каждым релизом искать обновление через поиск.
Потом скачивать обновление в папку загрузки, 
Потом заходить в раздел установки расширений открывать проводник, искать файл в проводнике в последних загрузка. а потом перетаскивать обновление?
И это вы предлагаете жителям России делать каждый раз для каждого сайта?
Вы жестоки. А ведь просто надо дать доступ к файлу обновлений в этой репе.

К официальному серверу всё  равно нет доступа, так что давайте сделаем НЕофицальный
