### ISSUE TITLE
Неверный DATE_FORMAT_LC6

### ISSUE THREAD

**Issue by Globulopolis** [JPathRu/localisation#99]
В англоязычной версии `DATE_FORMAT_LC6` оканчивается секундами. В русскоязычной почему-то без.

**Comment by Kostelano** [comment]
В Joomla есть небольшой хаос в отношении используемых констант времени - в материалах/категориях один, в пользователях - второй, в баннерах/контактах - третий и т.д. Нельзя решить общую проблему отображения времени простым добавлением секунд в константу `DATE_FORMAT_LC6` по вышеуказанной причине.

![Screenshot_1](https://github.com/JPathRu/localisation/assets/8440661/f5da1d99-b108-4d78-bc2f-3e9dbfbcce65)

Едва ли можно считать секунды необходимой информацией для, например, времени регистрации пользователя. Кроме того, секунды раздувают и без того широкие столбцы для русской локализации (да и для многих других локализаций на самом деле). Поэтому когда-то давно секунды намеренно были удалены из константы.

Если по какой-то причине вам действительно нужны секунды, просто воспользуйтесь переопределением констант - таким образом проще "выровнять" ситуацию по сайту и в используемых вами компонентах.

На сейчас все константы - без секунд:

```
; Date format
DATE_FORMAT_CALENDAR_DATE="%d.%m.%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d.%m.%Y, %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d.m.Y"
DATE_FORMAT_FILTER_DATETIME="d.m.Y, H:i:s"
DATE_FORMAT_JS1="d.m.Y"
DATE_FORMAT_LC="l, d F Y"
DATE_FORMAT_LC1="l, d F Y"
DATE_FORMAT_LC2="l, d F Y, H:i"
DATE_FORMAT_LC3="d F Y"
DATE_FORMAT_LC4="d.m.Y"
DATE_FORMAT_LC5="d.m.Y, H:i"
DATE_FORMAT_LC6="d.m.Y, H:i"
```
